### ISSUE TITLE
2021-12-07 Peer-to-peer code review

### ISSUE THREAD

**Issue by vechicin** [ivaan1992/To-Do-List#5]
# Hello Ivan, nice work! 👍 🤓 
I like the way your project looks and how smooth all of the functionalities are 
### Here are some things to consider

- Don't forget to update your README live demo link to make sure the user gets redirected to the GitHub Page as opposed to a full-screen version of the README.
- I noticed your clear all completed button doesn't remove just the completed tasks, it removes all of them, consider fixing that.

## Other than that I congratulate you on your project, nice job, keep it up! ✅

**Comment by iwillteixeira** [comment]
### Hi Ivan! you have been doing a good job.

**Some suggestions**

I think you will have to change the way the index values are been setting.
![image](https://user-images.githubusercontent.com/89435894/145047305-58572229-9326-4d3c-9070-c9297ccbb91e.png)
for this project, the reviewers ask to put it in order like id=1, id=2,id=3, also consider changing the name from id to index to avoid reviews problems, since it is asking in the project requirements.
